### ISSUE TITLE
Dashboard testing

### ISSUE THREAD

**Issue by lmazuel** [lmazuel/TestingRepo#15]

**Comment by lmazuel** [comment]
klsfjdlkjflksd
lskjflkdjf

**Comment by lmazuel** [comment]
MYHEADER
<details><summary>Swagger to SDK encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "D:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 29, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 97, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
MYHEADER
<details><summary>Swagger to SDK encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "D:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 29, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 97, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
MYHEADER
<details><summary>Swagger to SDK encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "D:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 29, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 97, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
MYHEADER
<details><summary>Swagger to SDK encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "d:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 29, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 97, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
MYHEADER
<details><summary>Swagger to SDK encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "d:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 29, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 97, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
MYHEADER
<details><summary>Swagger to SDK encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "d:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 29, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 97, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
MYHEADER
<details><summary>Swagger to SDK encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "D:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 29, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 97, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
# MYHEADER
<details><summary>Swagger to SDK encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "D:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 29, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 97, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
# MYHEADER
<details><summary>Swagger to SDK encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "D:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 29, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 98, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
# MYHEADER
New text comment

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER
New text comment

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER
<details><summary>Encountered an unknown error: (Python bot)</summary><p>

```python
Traceback (most recent call last):
  File "D:\VSProjects\swagger-to-sdk\swaggertosdk\github_tools.py", line 32, in exception_to_github
    yield context
  File "d:\VSProjects\swagger-to-sdk\tests\test_github_tools.py", line 110, in test_dashboard
    "Test".fakemethod(12)  # pylint: disable=no-member
AttributeError: 'str' object has no attribute 'fakemethod'

```

</p></details>

**Comment by lmazuel** [comment]
# MYHEADER
New text comment

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER

**Comment by lmazuel** [comment]
# MYHEADER
